spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LOL_Community
    username: root
    password: onlyroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  servlet:
    session:
      timeout: 15m
file:
  upload-dir: C:\Users\ksk69\desktop\바탕 화면\프로젝트\web\src\main\resources\static\uploadFile\
  img-path: C:\Users\ksk69\desktop\바탕 화면\프로젝트\web\src\main\resources\static\images\